# Generated by Django 5.0.14 on 2026-03-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], default='STUDENT', max_length=20)),
                ('message', models.TextField()),
                ('ai_response', models.TextField(blank=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
