# Generated by Django 5.0.14 on 2026-03-21 16:27

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('class_number', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('subtopics', models.JSONField(blank=True, default=list)),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('duration_minutes', models.PositiveIntegerField(default=90)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20)),
                ('is_ai_generated', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('class_number', 'order_index'),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('syllabus_pdf', models.FileField(blank=True, null=True, upload_to=apps.courses.models.syllabus_upload_path)),
                ('syllabus_text', models.TextField(blank=True)),
                ('syllabus_parse_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('num_assignments', models.PositiveIntegerField(default=2)),
                ('assignment_weightage', models.CharField(blank=True, max_length=100)),
                ('extracted_topics', models.JSONField(blank=True, default=list)),
                ('extracted_policies', models.JSONField(blank=True, default=list)),
                ('parse_metadata', models.JSONField(blank=True, default=dict)),
                ('schedule_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
