# Generated by Django 5.0.14 on 2026-03-22 09:31

import apps.courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Uploaded Material', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.courses.models.material_upload_path)),
                ('content_text', models.TextField(blank=True)),
                ('extracted_topics', models.JSONField(blank=True, default=list)),
                ('parse_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
