# Generated by Django 5.0.14 on 2026-03-25 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursematerial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher'], name='courses_cou_teacher_ef24fb_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_cou_status_158bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['course', '-created_at'], name='courses_cou_course__7a0b27_idx'),
        ),
    ]
