# Generated by Django 5.0.14 on 2026-03-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('MCQ', 'MCQ'), ('ESSAY', 'Essay'), ('CODING', 'Coding')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('total_marks', models.PositiveIntegerField(default=20)),
                ('questions', models.JSONField(default=list)),
                ('rubric', models.JSONField(blank=True, default=list)),
                ('answer_key', models.JSONField(blank=True, default=dict)),
                ('due_date', models.DateTimeField()),
                ('covered_until_class', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
