# Generated by Django 5.0.14 on 2026-04-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
        ('courses', '0005_course_invite_code_studentflashcard_studentnotebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_pdf',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course', '-created_at'], name='assignments_course__45b6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course', 'status'], name='assignments_course__dbd023_idx'),
        ),
    ]
