# Generated by Django 5.0.14 on 2026-04-09 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_course_invite_code_studentflashcard_studentnotebook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('LIVE', 'Live'), ('PRACTICE', 'Practice')], default='LIVE', max_length=20)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('low_score_threshold', models.PositiveIntegerField(default=60)),
                ('source_material_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.classschedule')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto Submitted')], default='IN_PROGRESS', max_length=20)),
                ('score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_practice', models.BooleanField(default=False)),
                ('feedback_released', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='QuizAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_SCORE', 'Low Score')], default='LOW_SCORE', max_length=20)),
                ('threshold_percent', models.FloatField(default=60)),
                ('actual_percent', models.FloatField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_alerts', to='courses.course')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='quizzes.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_alerts', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='quizzes.quizattempt')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(default='MEDIUM', max_length=20)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('AI_GENERATED', 'AI Generated'), ('TEACHER_EDITED', 'Teacher Edited'), ('TEACHER_ADDED', 'Teacher Added')], default='AI_GENERATED', max_length=30)),
                ('source_citation', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz')),
            ],
            options={
                'ordering': ('order_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=1)),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizzes.quizquestion')),
            ],
            options={
                'ordering': ('option_key',),
            },
        ),
        migrations.CreateModel(
            name='QuizAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_key', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='quizzes.quizquestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', 'session', 'state'], name='quizzes_qui_course__5ce008_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['creator', 'mode', '-created_at'], name='quizzes_qui_creator_470247_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'student'], name='quizzes_qui_quiz_id_68c200_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', '-started_at'], name='quizzes_qui_student_7fe522_idx'),
        ),
        migrations.AddIndex(
            model_name='quizalert',
            index=models.Index(fields=['course', 'is_read', '-created_at'], name='quizzes_qui_course__7f02ef_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'order_index'], name='quizzes_qui_quiz_id_d32c9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizoption',
            unique_together={('question', 'option_key')},
        ),
        migrations.AlterUniqueTogether(
            name='quizattemptanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
