# Generated by Django 5.0.14 on 2026-03-21 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded')], default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ai_grade', models.FloatField(default=0)),
                ('ai_feedback', models.JSONField(blank=True, default=dict)),
                ('score_breakdown', models.JSONField(blank=True, default=list)),
                ('grading_version', models.CharField(default='v1', max_length=50)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
    ]
