# Generated by Django 5.0.14 on 2026-04-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_submission_submissions_assignm_d45bb4_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="teacher_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="teacher_grade",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="teacher_graded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
